#!/usr/bin/env python3
# group: rw
#
# Test graph changes while I/O is happening
#
# Copyright (C) 2022 Red Hat, Inc.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

import os
import time
from threading import Thread
import iotests
from iotests import imgfmt, qemu_img, qemu_img_create, qemu_io, \
        QMPTestCase, QemuStorageDaemon


top = os.path.join(iotests.test_dir, 'top.img')
nbd_sock = os.path.join(iotests.sock_dir, 'nbd.sock')
test_img = os.path.join(iotests.test_dir, 'test.img')
target_img = os.path.join(iotests.test_dir, 'target.img')

def do_qemu_img_bench(count: int = 2000000) -> None:
    """
    Do some I/O requests on `nbd_sock`.
    """
    qemu_img('bench', '-f', 'raw', '-c', str(count),
             f'nbd+unix:///node0?socket={nbd_sock}')

def flatten_sock_addr(crumpled_address):
    result = { 'type': crumpled_address['type'] }
    result.update(crumpled_address['data'])
    return result

class TestGraphChangesWhileIO(QMPTestCase):
    def blockdev_add_options(self, address, export, node_name):
        options = { 'node-name': node_name,
                    'driver': 'raw',
                    'file': {
                        'driver': 'nbd',
                        'read-only': True,
                        'server': address
                    } }
        if export is not None:
            options['file']['export'] = export
        return options

    def setUp(self) -> None:
        # Create an overlay that can be added at runtime on top of the
        # null-co block node that will receive I/O
        qemu_img_create('-f', imgfmt, '-F', 'raw', '-b', 'null-co://', top)
        qemu_img_create('-f', imgfmt, test_img, '512')
        qemu_img_create('-f', imgfmt, target_img, '512')

        # QSD instance with a null-co block node in an I/O thread,
        # exported over NBD (on `nbd_sock`, export name "node0")
        self.qsd = QemuStorageDaemon(
            '--object', 'iothread,id=iothread0',
            '--blockdev', f'file,node-name=node1,filename={target_img}',
            '--nbd-server', f'addr.type=unix,addr.path={nbd_sock}',
            '--export', 'nbd,id=exp0,node-name=node1,iothread=iothread0,' +
                        'fixed-iothread=true,writable=true',
            qmp=True
        )

        self.vm = iotests.VM() #.add_drive(test_img)
        self.vm.launch()

    def tearDown(self) -> None:
        self.qsd.stop()
        os.remove(test_img)
        os.remove(target_img)

    def test_mirror_while_io(self) -> None:
        result = self.vm.qmp('object-add', qom_type='iothread', id='iothread0')
        self.assert_qmp(result, 'return', {})

        result = self.vm.qmp('blockdev-add', {
            'driver': imgfmt,
            'node-name': 'drive0',
            'file': {
                'driver': 'file',
                'filename': test_img,
            }
        })
        self.assert_qmp(result, 'return', {})

        result = self.vm.qmp('x-blockdev-set-iothread', {
            'node-name': 'drive0',
            'iothread': 'iothread0',
        })
        self.assert_qmp(result, 'return', {})

        result = self.vm.qmp('drive-mirror', device='drive0', sync='full',
                             target=f'nbd+unix:///node1?socket={nbd_sock}', mode='existing',
                             job_id='job0')
        self.assert_qmp(result, 'return', {})
        time.sleep(20)


if __name__ == '__main__':
    # Format must support raw backing files
    iotests.main(supported_fmts=['qcow', 'qcow2', 'qed'],
                 supported_protocols=['file'])
